name: 'Terraform'

on: push

env:
  TF_LOG: INFO
  TF_INPUT: false

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    permissions:
      id-token: write # <-- THIS IS THE CRUCIAL PERMISSION
      contents: read  # To checkout the repository code

    # Use the Bash shell regardless whether the GitHub Actions runner is 
    # ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the preferred version of Terraform CLI 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      id: init
      run: terraform init

    # Run a terraform fmt for push
    - name: Terraform Format
      id: fmt
      run: terraform fmt -check

    # Run a terraform validate
    # Run even if formatting fails
    - name: Terraform Validate
      id: validate
      if: (success() || failure())
      run: terraform validate


    # --- AWS Authentication ---
    # This step configures AWS credentials using OIDC.
    # Replace <YOUR_AWS_ACCOUNT_ID> and GitHubActions-Terraform-Deployer with your actual values.
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        # The ARN of the IAM Role you created for GitHub Actions in AWS
        # This role should have permissions to deploy your AWS resources (EC2, S3, DynamoDB, etc.)
        role-to-assume: arn:aws:iam::508140293808:role/GHA-Terraform-Infra
        aws-region: us-east-1 # Or whatever AWS region your infrastructure is in


    # Generate and show a Terraform execution plan
    # This step will run on all pushes and pull requests to show planned changes.
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      # Store the plan output as an environment variable to use in subsequent steps (e.g., PR comments)
      env:
        # GITHUB_TOKEN here is the default token provided by GitHub Actions for API interaction
        # It's not the same as your personal access token (PAT)
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Ensure this is present if using github-script action
      continue-on-error: true # Allow subsequent steps to run even if plan has errors
